services:
  db:
    platform: 'linux/amd64'
    container_name: verdd-db-django-local
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=verdd
      - MARIADB_DATABASE=verdd
      - MARIADB_USER=verdd
      - MARIADB_PASSWORD=verdd
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
  redis:
    platform: 'linux/amd64'
    container_name: verdd-redis
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    platform: 'linux/amd64'
    container_name: verdd-backend-django-local
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=verdd.settings.production
    volumes:
      - .:/app
      - verdd-files:/tmp/verdd_files
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  worker:
    platform: 'linux/amd64'
    container_name: verdd-celery-worker
    build: .
    command: celery -A verdd worker --loglevel=info
    volumes:
      - .:/app
      - verdd-files:/tmp/verdd_files
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
volumes:
  db-data:
  verdd-files:
