# Generated by Django 2.2.1 on 2019-06-11 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_source', models.CharField(max_length=3)),
                ('lang_target', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme', models.CharField(max_length=250)),
                ('homoId', models.IntegerField(default=0)),
                ('assonance', models.CharField(blank=True, max_length=250)),
                ('assonance_rev', models.CharField(blank=True, max_length=250)),
                ('consonance', models.CharField(blank=True, max_length=250)),
                ('consonance_rev', models.CharField(blank=True, max_length=250)),
                ('language', models.CharField(max_length=3)),
                ('pos', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('contlex', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=25)),
                ('inflexId', models.CharField(blank=True, max_length=25)),
                ('inflexType', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (99, 'X')], default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('imported_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageXML.DataFile')),
                ('lemmaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lemmaId_set', to='manageXML.Lexeme')),
            ],
            options={
                'unique_together': {('lexeme', 'pos', 'homoId', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Translation'), (1, 'Etymology'), (2, 'Compound'), (3, 'Derivation'), (99, 'Other')], default=0)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('checked', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('deleted', models.BooleanField(default=False)),
                ('lexeme_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_from_lexeme_set', to='manageXML.Lexeme')),
                ('lexeme_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_to_lexeme_set', to='manageXML.Lexeme')),
            ],
            options={
                'unique_together': {('lexeme_from', 'lexeme_to', 'type')},
            },
        ),
        migrations.CreateModel(
            name='MiniParadigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msd', models.CharField(max_length=25)),
                ('wordform', models.CharField(max_length=250)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSource',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('page', models.CharField(blank=True, max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('added_date', models.DateTimeField(blank=True, editable=False, verbose_name='date published')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Relation')),
            ],
            options={
                'verbose_name': 'historical source',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRelation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Translation'), (1, 'Etymology'), (2, 'Compound'), (3, 'Derivation'), (99, 'Other')], default=0)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('checked', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(blank=True, editable=False, verbose_name='date published')),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lexeme_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme')),
                ('lexeme_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme')),
            ],
            options={
                'verbose_name': 'historical relation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMiniParadigm',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('msd', models.CharField(max_length=25)),
                ('wordform', models.CharField(max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lexeme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme')),
            ],
            options={
                'verbose_name': 'historical mini paradigm',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLexeme',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lexeme', models.CharField(max_length=250)),
                ('homoId', models.IntegerField(default=0)),
                ('assonance', models.CharField(blank=True, max_length=250)),
                ('assonance_rev', models.CharField(blank=True, max_length=250)),
                ('consonance', models.CharField(blank=True, max_length=250)),
                ('consonance_rev', models.CharField(blank=True, max_length=250)),
                ('language', models.CharField(max_length=3)),
                ('pos', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('added_date', models.DateTimeField(blank=True, editable=False, verbose_name='date published')),
                ('contlex', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=25)),
                ('inflexId', models.CharField(blank=True, max_length=25)),
                ('inflexType', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (99, 'X')], default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imported_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.DataFile')),
                ('lemmaId', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme')),
            ],
            options={
                'verbose_name': 'historical lexeme',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExamples',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lexeme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme')),
            ],
            options={
                'verbose_name': 'historical examples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('page', models.CharField(blank=True, max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Relation')),
            ],
            options={
                'unique_together': {('relation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Lexeme')),
            ],
            options={
                'unique_together': {('lexeme', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Lexeme')),
            ],
            options={
                'unique_together': {('lexeme', 'title')},
            },
        ),
    ]
