# Generated by Django 2.2.1 on 2019-09-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallexeme",
            name="checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lexeme",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
