# Generated by Django 2.2.1 on 2019-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0002_auto_20190921_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallexeme',
            name='inflexType',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (99, 'X')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='inflexType',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (99, 'X')], default=None, null=True),
        ),
    ]
