# Generated by Django 2.2.1 on 2019-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0003_auto_20190923_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
