# Generated by Django 2.2.1 on 2019-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0003_auto_20190923_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='type',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalrelation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Käännös'), (1, 'Etymologia'), (2, 'Yhdyssana'), (3, 'Johdos'), (99, 'Muu')], default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Käännös'), (1, 'Etymologia'), (2, 'Yhdyssana'), (3, 'Johdos'), (99, 'Muu')], default=0),
        ),
    ]
