# Generated by Django 2.2.1 on 2019-05-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0004_auto_20190523_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='contlex',
            field=models.CharField(default=str, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='lemmaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageXML.Translation'),
        ),
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
