# Generated by Django 2.2.1 on 2019-05-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0005_auto_20190523_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='notes',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
