# Generated by Django 2.2.1 on 2019-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0005_auto_20191013_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrelation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Translation'), (1, 'Etymology'), (2, 'Compound'), (3, 'Derivation'), (4, 'Variation'), (99, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Translation'), (1, 'Etymology'), (2, 'Compound'), (3, 'Derivation'), (4, 'Variation'), (99, 'Other')], default=0),
        ),
    ]
