# Generated by Django 2.2.1 on 2019-05-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0006_element_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='inflexId',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='MiniParadigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msd', models.CharField(max_length=25)),
                ('wordform', models.CharField(max_length=250)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Translation')),
            ],
        ),
    ]
