# Generated by Django 2.2.1 on 2019-10-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0006_auto_20191013_1824"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="affiliation",
            unique_together={("lexeme", "title", "link", "type")},
        ),
    ]
