# Generated by Django 2.2.1 on 2019-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0008_historicalelement_historicaletymon_historicalminiparadigm_historicalsource_historicaltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
