# Generated by Django 2.2.1 on 2019-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0010_auto_20190602_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsource',
            name='notes',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='notes',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='notes',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
