# Generated by Django 2.2.1 on 2020-01-06 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageXML', '0011_historicalrelationexamples_relationexamples'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examples',
            new_name='Example',
        ),
        migrations.RenameModel(
            old_name='HistoricalRelationExamples',
            new_name='HistoricalExample',
        ),
        migrations.RenameModel(
            old_name='HistoricalExamples',
            new_name='HistoricalRelationExample',
        ),
        migrations.RenameModel(
            old_name='RelationExamples',
            new_name='RelationExample',
        ),
        migrations.AlterModelOptions(
            name='historicalexample',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical example'},
        ),
        migrations.AlterModelOptions(
            name='historicalrelationexample',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical relation example'},
        ),
        migrations.RemoveField(
            model_name='historicalexample',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='historicalrelationexample',
            name='lexeme',
        ),
        migrations.AddField(
            model_name='historicalexample',
            name='lexeme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Lexeme'),
        ),
        migrations.AddField(
            model_name='historicalrelationexample',
            name='relation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manageXML.Relation'),
        ),
    ]
