# Generated by Django 2.2.1 on 2019-06-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0011_auto_20190602_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageXML.Translation')),
            ],
        ),
    ]
