# Generated by Django 2.2.1 on 2019-06-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0012_affiliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='link',
            new_name='title',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='pageId',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
