# Generated by Django 2.2.1 on 2019-06-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0013_auto_20190602_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='pageId',
        ),
    ]
