# Generated by Django 2.2.1 on 2020-06-07 01:41

from django.db import migrations
import manageXML.fields


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0015_auto_20200602_0033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallexeme",
            name="lexeme_lang",
            field=manageXML.fields.BinaryCharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="lexeme",
            name="lexeme_lang",
            field=manageXML.fields.BinaryCharField(blank=True, max_length=250),
        ),
    ]
