# Generated by Django 2.2.1 on 2020-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0019_auto_20200616_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstem',
            name='homoId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stem',
            name='homoId',
            field=models.IntegerField(default=0),
        ),
    ]
