# Generated by Django 2.2.1 on 2020-07-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0019_auto_20200701_2023'),
        ('manageXML', '0026_auto_20200710_2245'),
    ]

    operations = [
    ]
