# Generated by Django 2.2.1 on 2021-08-10 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manageXML", "0028_auto_20200728_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallexememetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Type"),
                    (5, "defNative"),
                    (6, "Ignore"),
                    (7, "Geo"),
                    (8, "MWE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrelation",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Translation"),
                    (1, "Etymology"),
                    (2, "Compound"),
                    (3, "Derivation"),
                    (4, "Variation"),
                    (5, "Phraseology"),
                    (8, "Hyponymy"),
                    (9, "Hyperonymy"),
                    (10, "Holonymy"),
                    (11, "Meronymy"),
                    (12, "Co-hyponym"),
                    (6, "Synonym"),
                    (7, "Antonym"),
                    (99, "Other"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrelationmetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Semantic Type"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lexememetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Type"),
                    (5, "defNative"),
                    (6, "Ignore"),
                    (7, "Geo"),
                    (8, "MWE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Translation"),
                    (1, "Etymology"),
                    (2, "Compound"),
                    (3, "Derivation"),
                    (4, "Variation"),
                    (5, "Phraseology"),
                    (8, "Hyponymy"),
                    (9, "Hyperonymy"),
                    (10, "Holonymy"),
                    (11, "Meronymy"),
                    (12, "Co-hyponym"),
                    (6, "Synonym"),
                    (7, "Antonym"),
                    (99, "Other"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="relationmetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Semantic Type"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
