# Generated by Django 2.2.1 on 2021-08-10 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manageXML", "0028_auto_20200728_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallexememetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Type"),
                    (5, "defNative"),
                    (6, "Ignore"),
                    (7, "Geo"),
                    (8, "MWE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrelation",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Translation"),
                    (1, "Etymology"),
                    (2, "Compound"),
                    (3, "Derivation"),
                    (4, "Variation"),
                    (5, "Phraseology"),
                    (8, "Hyponymy"),
                    (9, "Hyperonymy"),
                    (10, "Holonymy"),
                    (11, "Meronymy"),
                    (12, "Co-hyponym"),
                    (6, "Synonym"),
                    (7, "Antonym"),
                    (99, "Other"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrelationmetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Semantic Type"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lexememetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Type"),
                    (5, "defNative"),
                    (6, "Ignore"),
                    (7, "Geo"),
                    (8, "MWE"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Translation"),
                    (1, "Etymology"),
                    (2, "Compound"),
                    (3, "Derivation"),
                    (4, "Variation"),
                    (5, "Phraseology"),
                    (8, "Hyponymy"),
                    (9, "Hyperonymy"),
                    (10, "Holonymy"),
                    (11, "Meronymy"),
                    (12, "Co-hyponym"),
                    (6, "Synonym"),
                    (7, "Antonym"),
                    (99, "Other"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="relationmetadata",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Generic"),
                    (1, "Specification"),
                    (3, "Gender"),
                    (4, "Semantic Type"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLanguageParadigm",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("pos", models.CharField(max_length=25)),
                ("form", models.CharField(blank=True, max_length=250)),
                ("mini", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manageXML.Language",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical language paradigm",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LanguageParadigm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos", models.CharField(max_length=25)),
                ("form", models.CharField(blank=True, max_length=250)),
                ("mini", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="language_paradigms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paradigms",
                        to="manageXML.Language",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "pos", "form")},
            },
        ),
    ]
