# Generated by Django 5.0.7 on 2024-08-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageXML', '0029_alter_historicalaffiliation_options_and_more'),
        ('manageXML', '0029_auto_20210810_2054'),
    ]

    operations = [
    ]
