# Generated by Django 5.1 on 2024-08-31 17:08

import django.db.models.deletion
from django.conf import settings
import manageXML.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0032_alter_affiliation_id_alter_datafile_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "LEXC"),
                            (2, "GIELLA_XML"),
                            (3, "APERTIUM_BIDIX"),
                            (4, "TRANSLATION_PREDICTIONS"),
                            (5, "LaTeX"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Generation Pending"),
                            ("processing", "Generation Processing"),
                            ("completed", "Generation Completed"),
                            ("failed", "Generation Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("options", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=manageXML.storage.TemporaryFileStorage,
                        upload_to="files/",
                    ),
                ),
                ("output", models.TextField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lang_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_requests_lang_source",
                        to="manageXML.language",
                    ),
                ),
                (
                    "lang_target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_requests_lang_target",
                        to="manageXML.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
