# Generated by Django 5.1 on 2024-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0033_filerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="id",
            field=models.CharField(
                db_index=True,
                max_length=3,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(fields=["id"], name="id_idx"),
        ),
    ]
