# Generated by Django 5.1.1 on 2024-09-08 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageXML", "0035_alter_historicalrelation_type_alter_relation_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(
                fields=["lexeme", "pos", "language"], name="lexeme_pos_language_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["lexeme"], name="lexeme_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["pos"], name="pos_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["language"], name="language_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["lexeme_lang"], name="lexeme_lang_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["consonance"], name="consonance_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["consonance_rev"], name="consonance_rev_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["assonance"], name="assonance_idx"),
        ),
        migrations.AddIndex(
            model_name="lexeme",
            index=models.Index(fields=["assonance_rev"], name="assonance_rev_idx"),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(fields=["lexeme_from"], name="lexeme_from_idx"),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(fields=["lexeme_to"], name="lexeme_to_idx"),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(fields=["type"], name="type_idx"),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(fields=["checked"], name="checked_idx"),
        ),
    ]
